name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - name: Create env file
        run: |
          touch .env
          echo VITE_APP_API_URL=${{ secrets.VITE_APP_API_URL }} >> .env
          echo VITE_APP_GOOGLE_ID=${{ secrets.VITE_APP_GOOGLE_ID }} >> .env
          cat .env
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DO_MORE_5B9F0 }}'
          channelId: live
          projectId: do-more-5b9f0
